#include "../../core/board.hpp"
#include "../../core/parameters.hpp"
#include "../../ai/lawliet.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <random>
#include <thread>
#include <mutex>
#include <iomanip>
#include <cassert>

struct PositionEntry {
    std::string fen;
    double result; // 1.0 = Win, 0.5 = Draw, 0.0 = Loss
};

struct SparseFeature {
    int32_t index;
    int16_t value;
};

using SparseVector = std::vector<SparseFeature>;

bool parse_epd_line(const std::string& line, std::string& fen, double& result) {
    if (line.empty()) return false;
    if (line.find("1-0") != std::string::npos) result = 1.0;
    else if (line.find("0-1") != std::string::npos) result = 0.0;
    else if (line.find("1/2-1/2") != std::string::npos) result = 0.5;
    else return false;

    size_t pos = line.find(";");
    if (pos == std::string::npos) pos = line.find("c0");
    if (pos == std::string::npos) pos = line.find("hmvc");

    if (pos != std::string::npos) {
        fen = line.substr(0, pos);
    } else {
        std::istringstream iss(line);
        std::string part;
        fen = "";
        for (int i = 0; i < 4; ++i) {
            if (iss >> part) fen += part + " ";
        }
    }
    return true;
}

void save_parameters_to_file(const std::string& filepath, const EvalParams& p) {
    std::ofstream out(filepath);
    out << "// This file is auto-generated by the Lawliet Texel Tuner.\n";
    out << "// Do not edit manually.\n\n";
    out << "#include \"parameters.hpp\"\n\n";
    out << "EvalParams g_Params = {\n";

    out << "    // Piece values\n";
    out << "    {";
    for (int i = 0; i < 5; ++i) out << p.pieceValuesMidgame[i] << (i < 4 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 5; ++i) out << p.pieceValuesEndgame[i] << (i < 4 ? ", " : "");
    out << "},\n\n";

    auto print_pst = [&](const std::string& name, const int* arr) {
        out << "    // " << name << "\n    {\n        ";
        for (int i = 0; i < 64; ++i) {
            out << arr[i] << (i < 63 ? ", " : "");
            if ((i + 1) % 8 == 0 && i < 63) out << "\n        ";
        }
        out << "\n    },\n";
    };

    print_pst("Pawn PST Midgame", p.pawnTableMidgame);
    print_pst("Pawn PST Endgame", p.pawnTableEndgame);
    print_pst("Knight PST Midgame", p.knightTableMidgame);
    print_pst("Knight PST Endgame", p.knightTableEndgame);
    print_pst("Bishop PST Midgame", p.bishopTableMidgame);
    print_pst("Bishop PST Endgame", p.bishopTableEndgame);
    print_pst("Rook PST Midgame", p.rookTableMidgame);
    print_pst("Rook PST Endgame", p.rookTableEndgame);
    print_pst("Queen PST Midgame", p.queenTableMidgame);
    print_pst("Queen PST Endgame", p.queenTableEndgame);
    print_pst("King PST Midgame", p.kingTableMidgame);
    print_pst("King PST Endgame", p.kingTableEndgame);

    out << "\n    // Basic Evaluation Terms\n";
    out << "    " << p.BishopPairMg << ", " << p.BishopPairEg << ",\n";
    out << "    " << p.DoubledPawnMg << ", " << p.DoubledPawnEg << ",\n";
    out << "    " << p.IsolatedPawnMg << ", " << p.IsolatedPawnEg << ",\n";
    out << "    " << p.BackwardPawnMg << ", " << p.BackwardPawnEg << ",\n";
    out << "    " << p.ConnectedPawnMg << ", " << p.ConnectedPawnEg << ",\n";
    out << "    " << p.ConnectedPawnDefendedMg << ", " << p.ConnectedPawnDefendedEg << ",\n";
    out << "    " << p.ConnectedPawnPhalanxMg << ", " << p.ConnectedPawnPhalanxEg << ",\n";

    out << "\n    // Passed Pawns\n    {";
    for (int i = 0; i < 8; ++i) out << p.PassedPawnRankMg[i] << (i < 7 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 8; ++i) out << p.PassedPawnRankEg[i] << (i < 7 ? ", " : "");
    out << "},\n";

    out << "    " << p.ConnectedPassedPawnMgBase << ", " << p.ConnectedPassedPawnMgFactor << ",\n";
    out << "    " << p.ConnectedPassedPawnEgBase << ", " << p.ConnectedPassedPawnEgFactor << ",\n";

    out << "    " << p.RookBehindFriendlyPassedPawnMg << ", " << p.RookBehindFriendlyPassedPawnEg << ",\n";
    out << "    " << p.RookBehindEnemyPassedPawnMg << ", " << p.RookBehindEnemyPassedPawnEg << ",\n";

    out << "    " << p.KingProximityToPassedPawnEg << ",\n";

    out << "    " << p.CenterPawnOccupancyMg << ",\n";
    out << "    " << p.PawnAttacksCentralRanksMg << ",\n";

    out << "    {";
    for (int i = 0; i < 5; ++i) out << p.PawnAttackingPieceMg[i] << (i < 4 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 5; ++i) out << p.PawnAttackingPieceEg[i] << (i < 4 ? ", " : "");
    out << "},\n";

    out << "    " << p.DoubledRooksOnFileMg << ", " << p.DoubledRooksOnFileEg << ",\n";

    out << "    " << p.RookOn7thRankMg << ", " << p.RookOn7thRankEg << ",\n";
    out << "    " << p.RookOn7thRankWithTargetMg << ", " << p.RookOn7thRankWithTargetEg << ",\n";
    out << "    " << p.DoubledRooksOn7thRankMg << ", " << p.DoubledRooksOn7thRankEg << ",\n";

    out << "    " << p.RookOnOpenFileMg << ", " << p.RookOnOpenFileEg << ",\n";
    out << "    " << p.RookOnSemiOpenFileMg << ", " << p.RookOnSemiOpenFileEg << ",\n";

    out << "    " << p.UndevelopedMinorPenaltyMg << ",\n";
    out << "    " << p.UndevelopedQueenPenaltyMg << ",\n";

    auto print_array = [&](const std::string& label, const int* arr, int size) {
        out << "    // " << label << "\n    {";
        for (int i = 0; i < size; ++i) out << arr[i] << (i < size - 1 ? ", " : "");
        out << "},\n";
    };

    print_array("Knight Mobility Mg", p.KnightMobilityMg, 9);
    print_array("Knight Mobility Eg", p.KnightMobilityEg, 9);
    print_array("Bishop Mobility Mg", p.BishopMobilityMg, 14);
    print_array("Bishop Mobility Eg", p.BishopMobilityEg, 14);
    print_array("Rook Mobility Mg", p.RookMobilityMg, 15);
    print_array("Rook Mobility Eg", p.RookMobilityEg, 15);
    print_array("Queen Mobility Mg", p.QueenMobilityMg, 28);
    print_array("Queen Mobility Eg", p.QueenMobilityEg, 28);

    out << "    " << p.DefendedMinorBonusMg << ", " << p.DefendedMinorBonusEg << ",\n";

    out << "    " << p.KnightOutpostUnattackableMg << ", " << p.KnightOutpostUnattackableEg << ",\n";
    out << "    " << p.KnightOutpostAttackableMg << ", " << p.KnightOutpostAttackableEg << ",\n";
    out << "    " << p.BishopOutpostDefendedMg << ", " << p.BishopOutpostDefendedEg << ",\n";

    out << "    " << p.UndefendedMinorPenaltyMg << ", " << p.UndefendedMinorPenaltyEg << ",\n";

    out << "    " << p.KingCentralizationEg << ",\n";

    out << "    " << p.KingFileOpenPenaltyMg << ", " << p.KingFileOpenPenaltyEg << ",\n";
    out << "    " << p.KingFileSemiOpenPenaltyMg << ", " << p.KingFileSemiOpenPenaltyEg << ",\n";
    out << "    " << p.KingFileEnemyMajorAttackPenaltyMg << ", " << p.KingFileEnemyMajorAttackPenaltyEg << ",\n";

    print_array("King Pawn Shield Distance Penalties Mg", p.KingPawnShieldDistancePenaltiesMg, 3);
    print_array("King Pawn Shield Distance Penalties Eg", p.KingPawnShieldDistancePenaltiesEg, 3);

    print_array("Pawn Storm Penalties Mg", p.PawnStormPenaltiesMg, 3);

    out << "    " << p.KingSubRankPenaltyMg << ",\n";

    out << "    " << p.KingZoneAttackWeightKnight << ",\n";
    out << "    " << p.KingZoneAttackWeightBishop << ",\n";
    out << "    " << p.KingZoneAttackWeightRook << ",\n";
    out << "    " << p.KingZoneAttackWeightQueen << ",\n";
    out << "    " << p.KingDangerScaleMg << ",\n";

    out << "    " << p.CastleWKMg << ",\n";
    out << "    " << p.CastleWQMg << ",\n";

    out << "    " << p.TempoBonus << "\n";
    out << "};\n";
}

int main(int argc, char* argv[]) {
    std::cout << "=== Lawliet Texel Tuning Framework ===" << std::endl;
    std::string filename = "zurichess_quiet.epd";
    if (argc > 1) {
        filename = argv[1];
    }

    std::cout << "Loading EPD dataset from: " << filename << std::endl;
    std::ifstream file(filename);
    if (!file) {
        std::cerr << "Error: Dataset file not found." << std::endl;
        return 1;
    }

    std::vector<PositionEntry> dataset;
    std::string line;
    while (std::getline(file, line)) {
        PositionEntry entry;
        if (parse_epd_line(line, entry.fen, entry.result)) {
            dataset.push_back(entry);
        }
    }
    std::cout << "Successfully parsed " << dataset.size() << " valid positions." << std::endl;

    std::vector<ParameterRef> refs = get_parameter_references(g_Params);
    std::cout << "Registered parameters for optimization: " << refs.size() << std::endl;

    // Split Dataset into Train/Validation
    std::mt19937 rng(42);
    std::shuffle(dataset.begin(), dataset.end(), rng);
    size_t val_size = dataset.size() / 10;
    size_t train_size = dataset.size() - val_size;

    std::vector<PositionEntry> train_set(dataset.begin(), dataset.begin() + train_size);
    std::vector<PositionEntry> val_set(dataset.begin() + train_size, dataset.end());

    std::cout << "Dataset split -> Train: " << train_size << " | Validation: " << val_size << std::endl;

    // Feature extraction over threads
    std::cout << "Pre-calculating sparse feature matrices..." << std::endl;
    std::vector<SparseVector> train_features(train_size);
    std::vector<double> train_base_scores(train_size);

    std::vector<SparseVector> val_features(val_size);
    std::vector<double> val_base_scores(val_size);

    auto extract_features_parallel = [&](const std::vector<PositionEntry>& set, std::vector<SparseVector>& out_feats, std::vector<double>& out_bases) {
        std::mutex mtx;
        size_t next_idx = 0;
        size_t total = set.size();

        auto worker = [&]() {
            Board board;
            Lawliet engine;
            std::vector<ParameterRef> local_refs = get_parameter_references(g_Params);

            while (true) {
                size_t idx = 0;
                {
                    std::lock_guard<std::mutex> lock(mtx);
                    if (next_idx >= total) return;
                    idx = next_idx++;
                    if (idx % 10000 == 0 && idx > 0) {
                        std::cout << "  Processed " << idx << " / " << total << " positions..." << std::endl;
                    }
                }

                board.loadFen(set[idx].fen);
                board.loadParams();

                int base_score = engine.evaluateBoard(board);
                out_bases[idx] = base_score;

                SparseVector features;
                for (size_t j = 0; j < local_refs.size(); ++j) {
                    // Skip non-linear King attack parameters
                    if (local_refs[j].name.rfind("KingZoneAttack", 0) == 0 ||
                        local_refs[j].name == "KingDangerScaleMg") {
                        continue;
                        }

                        int original_val = *local_refs[j].ptr;
                    *local_refs[j].ptr = original_val + 1;

                    bool is_cached = (local_refs[j].name.rfind("pawnTable", 0) == 0 ||
                    local_refs[j].name.rfind("knightTable", 0) == 0 ||
                    local_refs[j].name.rfind("bishopTable", 0) == 0 ||
                    local_refs[j].name.rfind("rookTable", 0) == 0 ||
                    local_refs[j].name.rfind("queenTable", 0) == 0 ||
                    local_refs[j].name.rfind("kingTable", 0) == 0 ||
                    local_refs[j].name.rfind("pieceValues", 0) == 0);
                    if (is_cached) {
                        board.loadParams();
                    }

                    int new_score = engine.evaluateBoard(board);

                    *local_refs[j].ptr = original_val;
                    if (is_cached) {
                        board.loadParams();
                    }

                    int diff = new_score - base_score;
                    if (diff != 0) {
                        features.push_back({static_cast<int32_t>(j), static_cast<int16_t>(diff)});
                    }
                }
                out_feats[idx] = features;
            }
        };

        std::vector<std::thread> threads;
        unsigned int num_threads = std::thread::hardware_concurrency();
        if (num_threads == 0) num_threads = 4;
        for (unsigned int i = 0; i < num_threads; ++i) {
            threads.emplace_back(worker);
        }
        for (auto& t : threads) t.join();
    };

        std::cout << "Extracting training features..." << std::endl;
        extract_features_parallel(train_set, train_features, train_base_scores);
        std::cout << "Extracting validation features..." << std::endl;
        extract_features_parallel(val_set, val_features, val_base_scores);

        // Initial sigmoid constant scaling factor search (K calibration)
        std::cout << "Calibrating sigmoid scale K..." << std::endl;
        double best_k = 1.13;
        double best_mse = 1e9;
        for (double k = 0.5; k <= 3.0; k += 0.01) {
            double mse = 0.0;
            double c = k * std::log(10.0) / 400.0;
            for (size_t i = 0; i < train_size; ++i) {
                double s = 1.0 / (1.0 + std::exp(-c * train_base_scores[i]));
                double diff = train_set[i].result - s;
                mse += diff * diff;
            }
            mse /= train_size;
            if (mse < best_mse) {
                best_mse = mse;
                best_k = k;
            }
        }
        std::cout << "Optimal calibration: K = " << std::fixed << std::setprecision(4) << best_k << " (Base Train MSE: " << best_mse << ")" << std::endl;

        double C = best_k * std::log(10.0) / 400.0;

        // Optimization Parameter vectors
        size_t num_params = refs.size();
        std::vector<double> theta(num_params, 0.0);
        std::vector<double> m(num_params, 0.0);
        std::vector<double> v(num_params, 0.0);

        // Hyperparameters
        const int epochs = 100;
        const double lr = 0.35;
        const double beta1 = 0.9;
        const double beta2 = 0.999;
        const double epsilon = 1e-8;
        const double l2_lambda = 1e-6; // Optional slight L2 regularization to ensure numeric stability

        std::cout << "\nStarting optimization loop (Adam)..." << std::endl;
        std::cout << "--------------------------------------------------------" << std::endl;
        std::cout << " Epoch | Train MSE  | Val MSE    | Param Changes" << std::endl;
        std::cout << "--------------------------------------------------------" << std::endl;

        double best_val_mse = 1e9;
        std::vector<double> best_theta(num_params, 0.0);

        for (int epoch = 1; epoch <= epochs; ++epoch) {
            // Evaluate predictions on current epoch
            std::vector<double> train_scores(train_size, 0.0);
            double train_mse = 0.0;

            // Multi-threaded MSE & Gradient aggregation
            std::vector<double> grad(num_params, 0.0);
            std::mutex grad_mtx;

            auto compute_gradient_chunk = [&](size_t start, size_t end) {
                std::vector<double> local_grad(num_params, 0.0);
                double local_train_mse = 0.0;

                for (size_t i = start; i < end; ++i) {
                    double score = train_base_scores[i];
                    for (const auto& f : train_features[i]) {
                        score += theta[f.index] * f.value;
                    }

                    double s = 1.0 / (1.0 + std::exp(-C * score));
                    double diff = train_set[i].result - s;
                    local_train_mse += diff * diff;

                    // Gradient component of sigmoid
                    double derivative = -2.0 * C * diff * s * (1.0 - s);
                    for (const auto& f : train_features[i]) {
                        local_grad[f.index] += derivative * f.value;
                    }
                }

                std::lock_guard<std::mutex> lock(grad_mtx);
                train_mse += local_train_mse;
                for (size_t j = 0; j < num_params; ++j) {
                    grad[j] += local_grad[j];
                }
            };

            std::vector<std::thread> optimizer_threads;
            unsigned int num_threads = std::thread::hardware_concurrency();
            if (num_threads == 0) num_threads = 4;
            size_t chunk_size = train_size / num_threads;

            for (unsigned int t = 0; t < num_threads; ++t) {
                size_t start = t * chunk_size;
                size_t end = (t == num_threads - 1) ? train_size : start + chunk_size;
                optimizer_threads.emplace_back(compute_gradient_chunk, start, end);
            }
            for (auto& t : optimizer_threads) t.join();

            train_mse /= train_size;

            // Apply L2 regularization contribution
            for (size_t j = 0; j < num_params; ++j) {
                grad[j] = (grad[j] / train_size) + l2_lambda * theta[j];
            }

            // Apply Adam update
            double max_change = 0.0;
            for (size_t j = 0; j < num_params; ++j) {
                m[j] = beta1 * m[j] + (1.0 - beta1) * grad[j];
                v[j] = beta2 * v[j] + (1.0 - beta2) * (grad[j] * grad[j]);

                double m_hat = m[j] / (1.0 - std::pow(beta1, epoch));
                double v_hat = v[j] / (1.0 - std::pow(beta2, epoch));

                double update = lr * m_hat / (std::sqrt(v_hat) + epsilon);
                theta[j] -= update;
                if (std::abs(update) > max_change) {
                    max_change = std::abs(update);
                }
            }

            // Evaluate on validation set
            double val_mse = 0.0;
            for (size_t i = 0; i < val_size; ++i) {
                double score = val_base_scores[i];
                for (const auto& f : val_features[i]) {
                    score += theta[f.index] * f.value;
                }
                double s = 1.0 / (1.0 + std::exp(-C * score));
                double diff = val_set[i].result - s;
                val_mse += diff * diff;
            }
            val_mse /= val_size;

            // Track and save the best parameter epoch
            if (val_mse < best_val_mse) {
                best_val_mse = val_mse;
                best_theta = theta;
            }

            std::cout << " " << std::setw(5) << epoch << " | "
            << std::setw(10) << std::fixed << std::setprecision(7) << train_mse << " | "
            << std::setw(10) << val_mse << " | "
            << "Max step: " << std::setprecision(4) << max_change << std::endl;
        }

        std::cout << "--------------------------------------------------------" << std::endl;
        std::cout << "Optimal epoch found with Validation MSE: " << best_val_mse << std::endl;

        // Apply best parameters back to the active configuration
        for (size_t j = 0; j < num_params; ++j) {
            *refs[j].ptr = refs[j].default_value + static_cast<int>(std::round(best_theta[j]));
        }

        std::cout << "Writing optimized parameters directly to source file..." << std::endl;
        save_parameters_to_file("src/core/parameters.cpp", g_Params);
        std::cout << "Texel Tuning Completed Successfully! Output written to parameters.cpp." << std::endl;

        return 0;
}
