#include "../../core/board.hpp"
#include "../../core/parameters.hpp"
#include "../../ai/lawliet.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <random>
#include <thread>
#include <mutex>
#include <iomanip>
#include <cassert>
#include <cstring>

struct PositionEntry {
    std::string fen;
    double result; // 1.0 = Win, 0.5 = Draw, 0.0 = Loss
};

struct SparseFeature {
    int32_t index;
    int16_t value;
};

using SparseVector = std::vector<SparseFeature>;

bool parse_epd_line(const std::string& line, std::string& fen, double& result) {
    if (line.empty()) return false;
    if (line.find("1-0") != std::string::npos) result = 1.0;
    else if (line.find("0-1") != std::string::npos) result = 0.0;
    else if (line.find("1/2-1/2") != std::string::npos) result = 0.5;
    else return false;

    // Extract only the first 4 FEN fields (position, side, castling, en-passant).
    // EPD lines may have extra operands (c0, c9, hmvc, etc.) after the FEN
    // that do not belong in a standard FEN string.
    std::istringstream iss(line);
    std::string part;
    fen = "";
    int fields = 0;
    while (iss >> part && fields < 4) {
        fen += part + " ";
        fields++;
    }
    return true;
}

// Recompute mgPst and egPst from scratch using current static PST arrays.
// Must be called after loadParams() when PST or piece-value parameters change,
// because evaluateBoard() reads the pre-computed mgPst/egPst which become stale
// whenever PST or piece-value tables are modified.
void recompute_pst(Board& board) {
    int mg = 0;
    int eg = 0;
    for (int i = 0; i < 12; ++i) {
        uint64_t bb = board.pieceBB[i];
        while (bb) {
            int sq = __builtin_ctzll(bb);
            bb &= bb - 1;
            bool is_white = (i < 6);
            int type = i % 6;
            int idx = is_white ? sq : ((7 - (sq / 8)) * 8 + (sq % 8));
            int m = Board::pieceValuesMidgame[type] + Board::pstMidgame[type][idx];
            int e = Board::pieceValuesEndgame[type] + Board::pstEndgame[type][idx];
            if (is_white) {
                mg += m;
                eg += e;
            } else {
                mg -= m;
                eg -= e;
            }
        }
    }
    board.mgPst = mg;
    board.egPst = eg;
}

void save_parameters_to_file(const std::string& filepath, const EvalParams& p) {
    std::ofstream out(filepath);
    out << "// This file is auto-generated by the Lawliet Texel Tuner.\n";
    out << "// Do not edit manually.\n\n";
    out << "#include \"parameters.hpp\"\n";
    out << "#include <string>\n\n";
    out << "EvalParams g_Params = {\n";

    out << "    // Piece values\n";
    out << "    {";
    for (int i = 0; i < 5; ++i) out << p.pieceValuesMidgame[i] << (i < 4 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 5; ++i) out << p.pieceValuesEndgame[i] << (i < 4 ? ", " : "");
    out << "},\n\n";

    auto print_pst = [&](const std::string& name, const int* arr) {
        out << "    // " << name << "\n    {\n        ";
        for (int i = 0; i < 64; ++i) {
            out << arr[i] << (i < 63 ? ", " : "");
            if ((i + 1) % 8 == 0 && i < 63) out << "\n        ";
        }
        out << "\n    },\n";
    };

    print_pst("Pawn PST Midgame", p.pawnTableMidgame);
    print_pst("Pawn PST Endgame", p.pawnTableEndgame);
    print_pst("Knight PST Midgame", p.knightTableMidgame);
    print_pst("Knight PST Endgame", p.knightTableEndgame);
    print_pst("Bishop PST Midgame", p.bishopTableMidgame);
    print_pst("Bishop PST Endgame", p.bishopTableEndgame);
    print_pst("Rook PST Midgame", p.rookTableMidgame);
    print_pst("Rook PST Endgame", p.rookTableEndgame);
    print_pst("Queen PST Midgame", p.queenTableMidgame);
    print_pst("Queen PST Endgame", p.queenTableEndgame);
    print_pst("King PST Midgame", p.kingTableMidgame);
    print_pst("King PST Endgame", p.kingTableEndgame);

    out << "\n    // Basic Evaluation Terms\n";
    out << "    " << p.BishopPairMg << ", " << p.BishopPairEg << ",\n";
    out << "    " << p.DoubledPawnMg << ", " << p.DoubledPawnEg << ",\n";
    out << "    " << p.IsolatedPawnMg << ", " << p.IsolatedPawnEg << ",\n";
    out << "    " << p.BackwardPawnMg << ", " << p.BackwardPawnEg << ",\n";
    out << "    " << p.ConnectedPawnMg << ", " << p.ConnectedPawnEg << ",\n";
    out << "    " << p.ConnectedPawnDefendedMg << ", " << p.ConnectedPawnDefendedEg << ",\n";
    out << "    " << p.ConnectedPawnPhalanxMg << ", " << p.ConnectedPawnPhalanxEg << ",\n";

    out << "\n    // Passed Pawns\n    {";
    for (int i = 0; i < 8; ++i) out << p.PassedPawnRankMg[i] << (i < 7 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 8; ++i) out << p.PassedPawnRankEg[i] << (i < 7 ? ", " : "");
    out << "},\n";

    out << "    " << p.ConnectedPassedPawnMgBase << ", " << p.ConnectedPassedPawnMgFactor << ",\n";
    out << "    " << p.ConnectedPassedPawnEgBase << ", " << p.ConnectedPassedPawnEgFactor << ",\n";

    out << "    " << p.RookBehindFriendlyPassedPawnMg << ", " << p.RookBehindFriendlyPassedPawnEg << ",\n";
    out << "    " << p.RookBehindEnemyPassedPawnMg << ", " << p.RookBehindEnemyPassedPawnEg << ",\n";

    out << "    " << p.KingProximityToPassedPawnEg << ",\n";

    out << "    " << p.CenterPawnOccupancyMg << ",\n";
    out << "    " << p.PawnAttacksCentralRanksMg << ",\n";

    out << "    {";
    for (int i = 0; i < 5; ++i) out << p.PawnAttackingPieceMg[i] << (i < 4 ? ", " : "");
    out << "},\n    {";
    for (int i = 0; i < 5; ++i) out << p.PawnAttackingPieceEg[i] << (i < 4 ? ", " : "");
    out << "},\n";

    out << "    " << p.DoubledRooksOnFileMg << ", " << p.DoubledRooksOnFileEg << ",\n";

    out << "    " << p.RookOn7thRankMg << ", " << p.RookOn7thRankEg << ",\n";
    out << "    " << p.RookOn7thRankWithTargetMg << ", " << p.RookOn7thRankWithTargetEg << ",\n";
    out << "    " << p.DoubledRooksOn7thRankMg << ", " << p.DoubledRooksOn7thRankEg << ",\n";

    out << "    " << p.RookOnOpenFileMg << ", " << p.RookOnOpenFileEg << ",\n";
    out << "    " << p.RookOnSemiOpenFileMg << ", " << p.RookOnSemiOpenFileEg << ",\n";

    out << "    " << p.UndevelopedMinorPenaltyMg << ",\n";
    out << "    " << p.UndevelopedQueenPenaltyMg << ",\n";

    auto print_array = [&](const std::string& label, const int* arr, int size) {
        out << "    // " << label << "\n    {";
        for (int i = 0; i < size; ++i) out << arr[i] << (i < size - 1 ? ", " : "");
        out << "},\n";
    };

    print_array("Knight Mobility Mg", p.KnightMobilityMg, 9);
    print_array("Knight Mobility Eg", p.KnightMobilityEg, 9);
    print_array("Bishop Mobility Mg", p.BishopMobilityMg, 14);
    print_array("Bishop Mobility Eg", p.BishopMobilityEg, 14);
    print_array("Rook Mobility Mg", p.RookMobilityMg, 15);
    print_array("Rook Mobility Eg", p.RookMobilityEg, 15);
    print_array("Queen Mobility Mg", p.QueenMobilityMg, 28);
    print_array("Queen Mobility Eg", p.QueenMobilityEg, 28);

    out << "    " << p.DefendedMinorBonusMg << ", " << p.DefendedMinorBonusEg << ",\n";

    out << "    " << p.KnightOutpostUnattackableMg << ", " << p.KnightOutpostUnattackableEg << ",\n";
    out << "    " << p.KnightOutpostAttackableMg << ", " << p.KnightOutpostAttackableEg << ",\n";
    out << "    " << p.BishopOutpostDefendedMg << ", " << p.BishopOutpostDefendedEg << ",\n";

    out << "    " << p.UndefendedMinorPenaltyMg << ", " << p.UndefendedMinorPenaltyEg << ",\n";

    out << "    " << p.KingCentralizationEg << ",\n";

    out << "    " << p.KingFileOpenPenaltyMg << ", " << p.KingFileOpenPenaltyEg << ",\n";
    out << "    " << p.KingFileSemiOpenPenaltyMg << ", " << p.KingFileSemiOpenPenaltyEg << ",\n";
    out << "    " << p.KingFileEnemyMajorAttackPenaltyMg << ", " << p.KingFileEnemyMajorAttackPenaltyEg << ",\n";

    print_array("King Pawn Shield Distance Penalties Mg", p.KingPawnShieldDistancePenaltiesMg, 3);
    print_array("King Pawn Shield Distance Penalties Eg", p.KingPawnShieldDistancePenaltiesEg, 3);

    print_array("Pawn Storm Penalties Mg", p.PawnStormPenaltiesMg, 3);

    out << "    " << p.KingSubRankPenaltyMg << ",\n";

    out << "    " << p.KingZoneAttackWeightKnight << ",\n";
    out << "    " << p.KingZoneAttackWeightBishop << ",\n";
    out << "    " << p.KingZoneAttackWeightRook << ",\n";
    out << "    " << p.KingZoneAttackWeightQueen << ",\n";
    out << "    " << p.KingDangerScaleMg << ",\n";

    out << "    " << p.CastleWKMg << ",\n";
    out << "    " << p.CastleWQMg << ",\n";

    out << "    " << p.TempoBonus << "\n";
    out << "};\n";
}

static bool is_pst_or_value_param(const std::string& name) {
    return (name.rfind("pawnTable", 0) == 0 ||
            name.rfind("knightTable", 0) == 0 ||
            name.rfind("bishopTable", 0) == 0 ||
            name.rfind("rookTable", 0) == 0 ||
            name.rfind("queenTable", 0) == 0 ||
            name.rfind("kingTable", 0) == 0 ||
            name.rfind("pieceValues", 0) == 0);
}

static bool is_king_attack_param(const std::string& name) {
    return (name.rfind("KingZoneAttack", 0) == 0 ||
            name == "KingDangerScaleMg");
}



int main(int argc, char* argv[]) {
    std::cout << "=== Lawliet Texel Tuning Framework ===" << std::endl;
    std::string filename = "zurichess_quiet.epd";
    if (argc > 1) {
        filename = argv[1];
    }

    std::cout << "Loading EPD dataset from: " << filename << std::endl;
    std::ifstream file(filename);
    if (!file) {
        std::cerr << "Error: Dataset file not found." << std::endl;
        return 1;
    }

    std::vector<PositionEntry> dataset;
    std::string line;
    while (std::getline(file, line)) {
        PositionEntry entry;
        if (parse_epd_line(line, entry.fen, entry.result)) {
            dataset.push_back(entry);
        }
    }
    std::cout << "Successfully parsed " << dataset.size() << " valid positions." << std::endl;

    std::vector<ParameterRef> refs = get_parameter_references(g_Params);
    std::cout << "Registered parameters for optimization: " << refs.size() << std::endl;

    // Split Dataset into Train/Validation
    std::mt19937 rng(42);
    std::shuffle(dataset.begin(), dataset.end(), rng);
    size_t val_size = dataset.size() / 10;
    size_t train_size = dataset.size() - val_size;

    std::vector<PositionEntry> train_set(dataset.begin(), dataset.begin() + train_size);
    std::vector<PositionEntry> val_set(dataset.begin() + train_size, dataset.end());

    std::cout << "Dataset split -> Train: " << train_size << " | Validation: " << val_size << std::endl;

    // Feature extraction
    // NOTE: This is single-threaded because the perturbation approach modifies
    // the global g_Params and Board::static arrays. Multi-threaded access would
    // cause data races and incorrect feature deltas.
    std::cout << "Pre-calculating sparse feature matrices..." << std::endl;
    std::vector<SparseVector> train_features(train_size);
    std::vector<double> train_base_scores(train_size);

    Board board;
    Lawliet engine;
    std::vector<ParameterRef> local_refs = get_parameter_references(g_Params);

    for (size_t i = 0; i < train_size; ++i) {
        board.loadFen(train_set[i].fen);

        int base_score = engine.evaluateBoard(board);
        train_base_scores[i] = base_score;

        SparseVector features;
        for (size_t j = 0; j < local_refs.size(); ++j) {
            if (is_king_attack_param(local_refs[j].name)) {
                continue;
            }

            int original_val = *local_refs[j].ptr;
            *local_refs[j].ptr = original_val + 1;

            bool is_cached = is_pst_or_value_param(local_refs[j].name);
            if (is_cached) {
                board.loadParams();
                recompute_pst(board);
            }

            int new_score = engine.evaluateBoard(board);

            *local_refs[j].ptr = original_val;
            if (is_cached) {
                board.loadParams();
                recompute_pst(board);
            }

            int diff = new_score - base_score;
            if (diff != 0) {
                features.push_back({static_cast<int32_t>(j), static_cast<int16_t>(diff)});
            }
        }
        train_features[i] = features;

        if ((i + 1) % 10000 == 0) {
            std::cout << "  Processed " << (i + 1) << " / " << train_size << " training positions..." << std::endl;
        }
    }

    std::cout << "Extracting validation features..." << std::endl;
    std::vector<SparseVector> val_features(val_size);
    std::vector<double> val_base_scores(val_size);

    for (size_t i = 0; i < val_size; ++i) {
        board.loadFen(val_set[i].fen);

        int base_score = engine.evaluateBoard(board);
        val_base_scores[i] = base_score;

        SparseVector features;
        for (size_t j = 0; j < local_refs.size(); ++j) {
            if (is_king_attack_param(local_refs[j].name)) {
                continue;
            }

            int original_val = *local_refs[j].ptr;
            *local_refs[j].ptr = original_val + 1;

            bool is_cached = is_pst_or_value_param(local_refs[j].name);
            if (is_cached) {
                board.loadParams();
                recompute_pst(board);
            }

            int new_score = engine.evaluateBoard(board);

            *local_refs[j].ptr = original_val;
            if (is_cached) {
                board.loadParams();
                recompute_pst(board);
            }

            int diff = new_score - base_score;
            if (diff != 0) {
                features.push_back({static_cast<int32_t>(j), static_cast<int16_t>(diff)});
            }
        }
        val_features[i] = features;

        if ((i + 1) % 10000 == 0) {
            std::cout << "  Processed " << (i + 1) << " / " << val_size << " validation positions..." << std::endl;
        }
    }

    // Initial sigmoid constant scaling factor search (K calibration)
    std::cout << "Calibrating sigmoid scale K..." << std::endl;
    double best_k = 1.13;
    double best_mse = 1e9;
    for (double k = 0.5; k <= 3.0; k += 0.01) {
        double mse = 0.0;
        double c = k * std::log(10.0) / 400.0;
        for (size_t i = 0; i < train_size; ++i) {
            double s = 1.0 / (1.0 + std::exp(-c * train_base_scores[i]));
            double diff = train_set[i].result - s;
            mse += diff * diff;
        }
        mse /= train_size;
        if (mse < best_mse) {
            best_mse = mse;
            best_k = k;
        }
    }
    std::cout << "Optimal calibration: K = " << std::fixed << std::setprecision(4) << best_k << " (Base Train MSE: " << best_mse << ")" << std::endl;

    double C = best_k * std::log(10.0) / 400.0;

    // Optimization Parameter vectors
    size_t num_params = refs.size();
    std::vector<double> theta(num_params, 0.0);
    std::vector<double> m(num_params, 0.0);
    std::vector<double> v(num_params, 0.0);

    // Hyperparameters
    const int epochs = 50;
    const int batch_size = 2048;
    const double base_lr = 0.35;
    const double beta1 = 0.9;
    const double beta2 = 0.999;
    const double epsilon = 1e-8;
    const double l2_lambda = 1e-6;
    const int early_stopping_patience = 5;

    std::cout << "\nStarting optimization loop (mini-batch Adam with cosine annealing)..." << std::endl;
    std::cout << "  Batch size: " << batch_size << " -> ~" << (train_size / batch_size) << " updates per epoch" << std::endl;
    std::cout << "  Learning rate schedule: cosine annealing from " << base_lr << " to 0" << std::endl;
    std::cout << "  Early stopping patience: " << early_stopping_patience << " epochs" << std::endl;
    std::cout << "--------------------------------------------------------" << std::endl;
    std::cout << " Epoch | Train MSE  | Val MSE    |   LR    | Updates" << std::endl;
    std::cout << "--------------------------------------------------------" << std::endl;

    double best_val_mse = 1e9;
    std::vector<double> best_theta(num_params, 0.0);
    int epochs_no_improve = 0;
    int total_updates = 0;

    // Pre-compute training index array for shuffling
    std::vector<size_t> train_indices(train_size);
    for (size_t i = 0; i < train_size; ++i) train_indices[i] = i;

    for (int epoch = 1; epoch <= epochs; ++epoch) {
        // Shuffle training indices for each epoch
        std::shuffle(train_indices.begin(), train_indices.end(), rng);

        // Cosine annealing: learning rate decays from base_lr to 0
        double cosine_progress = static_cast<double>(epoch - 1) / epochs;
        double lr = base_lr * 0.5 * (1.0 + std::cos(cosine_progress * M_PI));

        double epoch_train_mse = 0.0;
        size_t batches_in_epoch = 0;

        // Mini-batch loop
        for (size_t batch_start = 0; batch_start < train_size; batch_start += batch_size) {
            size_t batch_end = std::min(batch_start + batch_size, train_size);
            size_t batch_actual = batch_end - batch_start;

            // Compute gradient over this mini-batch
            std::vector<double> grad(num_params, 0.0);
            double batch_mse = 0.0;

            for (size_t b = batch_start; b < batch_end; ++b) {
                size_t idx = train_indices[b];
                double score = train_base_scores[idx];
                for (const auto& f : train_features[idx]) {
                    score += theta[f.index] * f.value;
                }

                double s = 1.0 / (1.0 + std::exp(-C * score));
                double diff = train_set[idx].result - s;
                batch_mse += diff * diff;

                double derivative = -2.0 * C * diff * s * (1.0 - s);
                for (const auto& f : train_features[idx]) {
                    grad[f.index] += derivative * f.value;
                }
            }

            batch_mse /= batch_actual;
            epoch_train_mse += batch_mse * batch_actual;

            // Average the gradient over the batch and add L2 regularization
            for (size_t j = 0; j < num_params; ++j) {
                grad[j] = (grad[j] / batch_actual) + l2_lambda * theta[j];
            }

            // Adam update
            total_updates++;
            for (size_t j = 0; j < num_params; ++j) {
                m[j] = beta1 * m[j] + (1.0 - beta1) * grad[j];
                v[j] = beta2 * v[j] + (1.0 - beta2) * (grad[j] * grad[j]);

                double m_hat = m[j] / (1.0 - std::pow(beta1, total_updates));
                double v_hat = v[j] / (1.0 - std::pow(beta2, total_updates));

                theta[j] -= lr * m_hat / (std::sqrt(v_hat) + epsilon);
            }

            batches_in_epoch++;
        }

        epoch_train_mse /= train_size;

        // Evaluate on validation set
        double val_mse = 0.0;
        for (size_t i = 0; i < val_size; ++i) {
            double score = val_base_scores[i];
            for (const auto& f : val_features[i]) {
                score += theta[f.index] * f.value;
            }
            double s = 1.0 / (1.0 + std::exp(-C * score));
            double diff = val_set[i].result - s;
            val_mse += diff * diff;
        }
        val_mse /= val_size;

        // Track and save the best parameter epoch
        if (val_mse < best_val_mse) {
            best_val_mse = val_mse;
            best_theta = theta;
            epochs_no_improve = 0;
        } else {
            epochs_no_improve++;
        }

        std::cout << " " << std::setw(5) << epoch << " | "
        << std::setw(10) << std::fixed << std::setprecision(6) << epoch_train_mse << " | "
        << std::setw(10) << val_mse << " | "
        << std::setw(6) << std::setprecision(4) << lr << " | "
        << std::setw(7) << total_updates << std::endl;

        if (epochs_no_improve >= early_stopping_patience) {
            std::cout << "  Early stopping triggered (no improvement for " << early_stopping_patience << " epochs)." << std::endl;
            break;
        }
    }

    std::cout << "--------------------------------------------------------" << std::endl;
    std::cout << "Total parameter updates: " << total_updates << std::endl;
    std::cout << "Optimal epoch found with Validation MSE: " << best_val_mse << std::endl;

    // Apply best parameters back to the active configuration
    for (size_t j = 0; j < num_params; ++j) {
        *refs[j].ptr = refs[j].default_value + static_cast<int>(std::round(best_theta[j]));
    }

    std::cout << "Writing optimized parameters directly to source file..." << std::endl;
    save_parameters_to_file("src/core/parameters.cpp", g_Params);
    std::cout << "Texel Tuning Completed Successfully! Output written to parameters.cpp." << std::endl;

    return 0;
}
