// This file is auto-generated by the Lawliet Texel Tuner.
// Do not edit manually.

#include "parameters.hpp"
#include <string>

EvalParams g_Params = {
    // Piece values
    {100, 325, 330, 500, 975},
    {100, 320, 325, 510, 950},

    // Pawn PST Midgame
    {
        0, 0, 0, 0, 0, 0, 0, 0, 
        100, 100, 92, 98, 98, 92, 100, 100, 
        -7, 3, 26, 34, 34, 26, 3, -7, 
        -37, -2, -11, 5, 5, -11, -2, -37, 
        -43, -14, -20, -1, -1, -20, -14, -43, 
        -36, -5, -17, -19, -19, -17, -5, -36, 
        -45, -2, -18, -36, -36, -18, -2, -45, 
        0, 0, 0, 0, 0, 0, 0, 0
    },
    // Pawn PST Endgame
    {
        0, 0, 0, 0, 0, 0, 0, 0, 
        130, 130, 128, 117, 117, 128, 130, 130, 
        77, 84, 56, 48, 48, 56, 84, 77, 
        18, 11, 0, -10, -10, 0, 11, 18, 
        -2, -3, -14, -18, -18, -14, -3, -2, 
        -10, -7, -15, -8, -8, -15, -7, -10, 
        -4, -4, -2, 2, 2, -2, -4, -4, 
        0, 0, 0, 0, 0, 0, 0, 0
    },
    // Knight PST Midgame
    {
        -100, -86, -80, 3, 3, -80, -86, -100, 
        -67, -32, 55, 14, 14, 55, -32, -67, 
        -13, 55, 49, 70, 70, 49, 55, -13, 
        4, 10, 32, 33, 33, 32, 10, 4, 
        -18, 6, 10, 10, 10, 10, 6, -18, 
        -23, 1, 9, 7, 7, 9, 1, -23, 
        -29, -45, -9, -7, -7, -9, -45, -29, 
        -68, -23, -46, -33, -33, -46, -23, -68
    },
    // Knight PST Endgame
    {
        -100, -59, -32, -50, -50, -32, -59, -100, 
        -48, -30, -46, -24, -24, -46, -30, -48, 
        -51, -40, -15, -21, -21, -15, -40, -51, 
        -37, -15, -3, 2, 2, -3, -15, -37, 
        -38, -21, -3, 2, 2, -3, -21, -38, 
        -44, -31, -24, -9, -9, -24, -31, -44, 
        -62, -38, -34, -25, -25, -34, -38, -62, 
        -65, -75, -38, -38, -38, -38, -75, -65
    },
    // Bishop PST Midgame
    {
        -23, -2, -60, -51, -51, -60, -2, -23, 
        -40, 15, 12, 9, 9, 12, 15, -40, 
        -8, 41, 46, 42, 42, 46, 41, -8, 
        1, 6, 30, 47, 47, 30, 6, 1, 
        -2, 13, 15, 30, 30, 15, 13, -2, 
        8, 19, 24, 17, 17, 24, 19, 8, 
        9, 28, 18, 6, 6, 18, 28, 9, 
        -28, -7, -9, -19, -19, -9, -7, -28
    },
    // Bishop PST Endgame
    {
        -29, -29, -18, -13, -13, -18, -29, -29, 
        -17, -17, -13, -19, -19, -13, -17, -17, 
        -10, -20, -12, -17, -17, -12, -20, -10, 
        -13, -5, -3, -4, -4, -3, -5, -13, 
        -19, -13, -3, 0, 0, -3, -13, -19, 
        -26, -18, -9, -2, -2, -9, -18, -26, 
        -35, -32, -21, -10, -10, -21, -32, -35, 
        -32, -22, -36, -17, -17, -36, -22, -32
    },
    // Rook PST Midgame
    {
        15, 20, 20, 25, 25, 20, 20, 15, 
        20, 25, 25, 30, 30, 25, 25, 20, 
        5, 10, 15, 20, 20, 15, 10, 5, 
        -10, -5, 5, 10, 10, 5, -5, -10, 
        -20, -10, 0, 5, 5, 0, -10, -20, 
        -25, -15, -5, 0, 0, -5, -15, -25, 
        -30, -20, -10, -5, -5, -10, -20, -30, 
        -15, -10, 0, 10, 10, 0, -10, -15
    },
    // Rook PST Endgame
    {
        8, 3, 15, 10, 10, 15, 3, 8, 
        4, 7, 2, 1, 1, 2, 7, 4, 
        4, 0, 0, 3, 3, 0, 0, 4, 
        7, 3, 8, 0, 0, 8, 3, 7, 
        1, 2, 5, 1, 1, 5, 2, 1, 
        -3, -1, -6, -3, -3, -6, -1, -3, 
        0, -7, -1, -1, -1, -1, -7, 0, 
        -12, 5, 2, -1, -1, 2, 5, -12
    },
    // Queen PST Midgame
    {
        -10, -5, -5, -5, -5, -5, -5, -10, 
        -5, 0, 0, 0, 0, 0, 0, -5, 
        -5, 0, 5, 5, 5, 5, 0, -5, 
        -5, 0, 5, 10, 10, 5, 0, -5, 
        -5, 0, 5, 10, 10, 5, 0, -5, 
        -5, 0, 5, 5, 5, 5, 0, -5, 
        -10, -5, 5, 5, 5, 5, -5, -10, 
        -10, -5, -5, 5, 5, -5, -5, -10
    },
    // Queen PST Endgame
    {
        -4, 8, 13, 18, 18, 13, 8, -4, 
        -16, 29, 25, 49, 49, 25, 29, -16, 
        -23, -10, 20, 50, 50, 20, -10, -23, 
        6, 42, 27, 52, 52, 27, 42, 6, 
        -11, 28, 23, 43, 43, 23, 28, -11, 
        -9, -27, 11, 3, 3, 11, -27, -9, 
        -31, -37, -46, -19, -19, -46, -37, -31, 
        -48, -38, -33, -50, -50, -33, -38, -48
    },
    // King PST Midgame
    {
        -5, 10, 10, -13, -13, 10, 10, -5, 
        0, 3, 10, 0, 0, 10, 3, 0, 
        17, 10, 10, -12, -12, 10, 10, 17, 
        -36, -4, -7, -26, -26, -7, -4, -36, 
        -63, -27, -48, -85, -85, -48, -27, -63, 
        -14, -4, -35, -57, -57, -35, -4, -14, 
        43, 32, -15, -45, -45, -15, 32, 43, 
        47, 60, 1, 29, 29, 1, 60, 47
    },
    // King PST Endgame
    {
        -38, -18, -11, -22, -22, -11, -18, -38, 
        -6, 11, 15, 6, 6, 15, 11, -6, 
        -1, 24, 24, 9, 9, 24, 24, -1, 
        -6, 15, 20, 20, 20, 20, 15, -6, 
        -14, 0, 19, 29, 29, 19, 0, -14, 
        -18, -4, 11, 21, 21, 11, -4, -18, 
        -37, -21, 0, 9, 9, 0, -21, -37, 
        -70, -47, -26, -42, -42, -26, -47, -70
    },

    // Basic Evaluation Terms
    30, 65,
    -22, -27,
    -21, -26,
    -21, -25,
    3, 1,
    8, 14,
    3, 5,

    // Passed Pawns
    {0, 150, 100, 60, 30, 15, 5, 0},
    {0, 320, 239, 149, 89, 39, 14, 0},
    24, 4,
    48, 11,
    20, 35,
    -10, -20,
    16,
    14,
    -4,
    {40, 40, 60, 100, 40},
    {30, 30, 45, 80, 30},
    16, 23,
    20, 30,
    44, 59,
    35, 50,
    19, 28,
    10, 15,
    13,
    17,
    // Knight Mobility Mg
    {0, 4, 8, 12, 16, 19, 24, 28, 32},
    // Knight Mobility Eg
    {0, 4, 8, 12, 16, 20, 24, 28, 32},
    // Bishop Mobility Mg
    {0, 3, 6, 9, 12, 15, 18, 20, 24, 27, 30, 33, 36, 39},
    // Bishop Mobility Eg
    {0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39},
    // Rook Mobility Mg
    {1, 2, 3, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28},
    // Rook Mobility Eg
    {0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 55},
    // Queen Mobility Mg
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27},
    // Queen Mobility Eg
    {0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54},
    12, 9,
    23, 14,
    10, 5,
    14, 9,
    -10, -8,
    1,
    60, 21,
    39, 13,
    24, 9,
    // King Pawn Shield Distance Penalties Mg
    {10, 25, 35},
    // King Pawn Shield Distance Penalties Eg
    {5, 9, 15},
    // Pawn Storm Penalties Mg
    {9, 25, 50},
    25,
    2,
    2,
    3,
    4,
    2,
    15,
    10,
    15
};

std::vector<ParameterRef> get_parameter_references(EvalParams& p) {
    std::vector<ParameterRef> refs;
    refs.reserve(EXPECTED_PARAMETER_COUNT);

    #define ADD_PARAM(name) refs.push_back({#name, &p.name, p.name})
    #define ADD_PARAM_ARR(name, size) \
    for (size_t i = 0; i < size; ++i) { \
        refs.push_back({std::string(#name) + "[" + std::to_string(i) + "]", &p.name[i], p.name[i]}); \
    }

    // Piece values
    ADD_PARAM_ARR(pieceValuesMidgame, 5);
    ADD_PARAM_ARR(pieceValuesEndgame, 5);

    // PST Tables
    ADD_PARAM_ARR(pawnTableMidgame, 64);
    ADD_PARAM_ARR(pawnTableEndgame, 64);
    ADD_PARAM_ARR(knightTableMidgame, 64);
    ADD_PARAM_ARR(knightTableEndgame, 64);
    ADD_PARAM_ARR(bishopTableMidgame, 64);
    ADD_PARAM_ARR(bishopTableEndgame, 64);
    ADD_PARAM_ARR(rookTableMidgame, 64);
    ADD_PARAM_ARR(rookTableEndgame, 64);
    ADD_PARAM_ARR(queenTableMidgame, 64);
    ADD_PARAM_ARR(queenTableEndgame, 64);
    ADD_PARAM_ARR(kingTableMidgame, 64);
    ADD_PARAM_ARR(kingTableEndgame, 64);

    // Positional / Pawn Terms
    ADD_PARAM(BishopPairMg); ADD_PARAM(BishopPairEg);
    ADD_PARAM(DoubledPawnMg); ADD_PARAM(DoubledPawnEg);
    ADD_PARAM(IsolatedPawnMg); ADD_PARAM(IsolatedPawnEg);
    ADD_PARAM(BackwardPawnMg); ADD_PARAM(BackwardPawnEg);
    ADD_PARAM(ConnectedPawnMg); ADD_PARAM(ConnectedPawnEg);
    ADD_PARAM(ConnectedPawnDefendedMg); ADD_PARAM(ConnectedPawnDefendedEg);
    ADD_PARAM(ConnectedPawnPhalanxMg); ADD_PARAM(ConnectedPawnPhalanxEg);

    // Passed Pawns
    ADD_PARAM_ARR(PassedPawnRankMg, 8);
    ADD_PARAM_ARR(PassedPawnRankEg, 8);

    ADD_PARAM(ConnectedPassedPawnMgBase); ADD_PARAM(ConnectedPassedPawnMgFactor);
    ADD_PARAM(ConnectedPassedPawnEgBase); ADD_PARAM(ConnectedPassedPawnEgFactor);

    ADD_PARAM(RookBehindFriendlyPassedPawnMg); ADD_PARAM(RookBehindFriendlyPassedPawnEg);
    ADD_PARAM(RookBehindEnemyPassedPawnMg); ADD_PARAM(RookBehindEnemyPassedPawnEg);

    ADD_PARAM(KingProximityToPassedPawnEg);

    ADD_PARAM(CenterPawnOccupancyMg);
    ADD_PARAM(PawnAttacksCentralRanksMg);

    ADD_PARAM_ARR(PawnAttackingPieceMg, 5);
    ADD_PARAM_ARR(PawnAttackingPieceEg, 5);

    // Rook Activity
    ADD_PARAM(DoubledRooksOnFileMg); ADD_PARAM(DoubledRooksOnFileEg);

    ADD_PARAM(RookOn7thRankMg); ADD_PARAM(RookOn7thRankEg);
    ADD_PARAM(RookOn7thRankWithTargetMg); ADD_PARAM(RookOn7thRankWithTargetEg);
    ADD_PARAM(DoubledRooksOn7thRankMg); ADD_PARAM(DoubledRooksOn7thRankEg);

    ADD_PARAM(RookOnOpenFileMg); ADD_PARAM(RookOnOpenFileEg);
    ADD_PARAM(RookOnSemiOpenFileMg); ADD_PARAM(RookOnSemiOpenFileEg);

    // Development
    ADD_PARAM(UndevelopedMinorPenaltyMg);
    ADD_PARAM(UndevelopedQueenPenaltyMg);

    // Mobility
    ADD_PARAM_ARR(KnightMobilityMg, 9);
    ADD_PARAM_ARR(KnightMobilityEg, 9);
    ADD_PARAM_ARR(BishopMobilityMg, 14);
    ADD_PARAM_ARR(BishopMobilityEg, 14);
    ADD_PARAM_ARR(RookMobilityMg, 15);
    ADD_PARAM_ARR(RookMobilityEg, 15);
    ADD_PARAM_ARR(QueenMobilityMg, 28);
    ADD_PARAM_ARR(QueenMobilityEg, 28);

    // Outposts / Defense
    ADD_PARAM(DefendedMinorBonusMg); ADD_PARAM(DefendedMinorBonusEg);

    ADD_PARAM(KnightOutpostUnattackableMg); ADD_PARAM(KnightOutpostUnattackableEg);
    ADD_PARAM(KnightOutpostAttackableMg); ADD_PARAM(KnightOutpostAttackableEg);
    ADD_PARAM(BishopOutpostDefendedMg); ADD_PARAM(BishopOutpostDefendedEg);

    ADD_PARAM(UndefendedMinorPenaltyMg); ADD_PARAM(UndefendedMinorPenaltyEg);

    // King safety and positioning
    ADD_PARAM(KingCentralizationEg);

    ADD_PARAM(KingFileOpenPenaltyMg); ADD_PARAM(KingFileOpenPenaltyEg);
    ADD_PARAM(KingFileSemiOpenPenaltyMg); ADD_PARAM(KingFileSemiOpenPenaltyEg);
    ADD_PARAM(KingFileEnemyMajorAttackPenaltyMg); ADD_PARAM(KingFileEnemyMajorAttackPenaltyEg);

    ADD_PARAM_ARR(KingPawnShieldDistancePenaltiesMg, 3);
    ADD_PARAM_ARR(KingPawnShieldDistancePenaltiesEg, 3);

    ADD_PARAM_ARR(PawnStormPenaltiesMg, 3);

    ADD_PARAM(KingSubRankPenaltyMg);

    // King zone attack values
    ADD_PARAM(KingZoneAttackWeightKnight);
    ADD_PARAM(KingZoneAttackWeightBishop);
    ADD_PARAM(KingZoneAttackWeightRook);
    ADD_PARAM(KingZoneAttackWeightQueen);
    ADD_PARAM(KingDangerScaleMg);

    ADD_PARAM(CastleWKMg);
    ADD_PARAM(CastleWQMg);

    ADD_PARAM(TempoBonus);

    #undef ADD_PARAM
    #undef ADD_PARAM_ARR

    return refs;
}
